/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface LoginChallenges {
  attempts: Generated<number>;
  code_digest: string;
  consumed_at: Timestamp | null;
  created_at: Timestamp;
  delivered_at: Timestamp | null;
  email: string;
  expires_at: Timestamp;
  flow_id: string;
  id: string;
  invalidated_at: Timestamp | null;
  link_hash: string;
}

export interface LoginFlows {
  binding_hash: string;
  created_at: Timestamp;
  csrf_hash: string;
  email: string | null;
  expires_at: Timestamp;
  id: string;
}

export interface OauthFlows {
  browser_hash: string;
  consumed_at: Timestamp | null;
  created_at: Timestamp;
  expires_at: Timestamp;
  link_session_hash: string | null;
  link_user_id: string | null;
  provider: string;
  redirect_uri: string;
  state_hash: string;
}

export interface OauthIdentities {
  created_at: Timestamp;
  provider: string;
  subject: string;
  user_id: string;
}

export interface RateLimits {
  count: number;
  key: string;
  window_start: Timestamp;
}

export interface Sessions {
  created_at: Timestamp;
  csrf_hash: string;
  expires_at: Timestamp;
  revoked_at: Timestamp | null;
  token_hash: string;
  user_id: string;
}

export interface Users {
  created_at: Timestamp;
  email: string;
  id: string;
}

export interface DB {
  login_challenges: LoginChallenges;
  login_flows: LoginFlows;
  oauth_flows: OauthFlows;
  oauth_identities: OauthIdentities;
  rate_limits: RateLimits;
  sessions: Sessions;
  users: Users;
}
